Repository Quantipy/quantipy, pull requests merged in 2018-10, with the labels that each got.

#1145 new code to detect numeric arrays
  quantipy/core/stack.py
Labels: bug, stack

#1148 I1141 sort weight specs
  quantipy/core/dataset.py
  quantipy/core/rules.py
  quantipy/sandbox/sandbox.py
  setup.py
  tests/test_dataset.py
Labels: ChainManager, DataSet, to do

#1160 correct local name sort_on_stat replaced
  quantipy/core/rules.py
Labels: bug, stack

#1162 I1161 bug in paint structure
  .gitignore
  quantipy/sandbox/sandbox.py
  setup.cfg
Labels: bug

#1164 I1027 cm arithmetics
  .pytest_cache/README.md
  .pytest_cache/v/cache/nodeids
  docs/API/_build/doctrees/environment.pickle
  docs/API/_build/doctrees/sites/api_ref/Chain.doctree
  docs/API/_build/doctrees/sites/api_ref/DataSet.doctree
  docs/API/_build/doctrees/sites/api_ref/QuantipyViews.doctree
  docs/API/_build/doctrees/sites/api_ref/Rim_scheme.doctree
  docs/API/_build/doctrees/sites/api_ref/View.doctree
  docs/API/_build/doctrees/sites/api_ref/quantify_engine.doctree
  docs/API/_build/doctrees/sites/api_ref/stack.doctree
  docs/API/_build/doctrees/sites/lib_doc/dataprocessing/00_overview.doctree
  docs/API/_build/doctrees/sites/lib_doc/dataprocessing/03_inspection.doctree
  docs/API/_build/doctrees/sites/release_notes/01_latest.doctree
  docs/API/_build/doctrees/sites/release_notes/02_archive.doctree
  docs/API/_build/html/_sources/sites/release_notes/01_latest.rst.txt
  docs/API/_build/html/_sources/sites/release_notes/02_archive.rst.txt
  docs/API/_build/html/genindex.html
  docs/API/_build/html/index.html
  docs/API/_build/html/objects.inv
  docs/API/_build/html/search.html
  docs/API/_build/html/searchindex.js
  docs/API/_build/html/sites/api_ref/00overview.html
  docs/API/_build/html/sites/api_ref/Chain.html
  docs/API/_build/html/sites/api_ref/DataSet.html
  docs/API/_build/html/sites/api_ref/QuantipyViews.html
  docs/API/_build/html/sites/api_ref/Rim_scheme.html
  docs/API/_build/html/sites/api_ref/View.html
  docs/API/_build/html/sites/api_ref/quantify_engine.html
  docs/API/_build/html/sites/api_ref/stack.html
  docs/API/_build/html/sites/lib_doc/dataprocessing/00_overview.html
  docs/API/_build/html/sites/lib_doc/dataprocessing/01_components.html
  docs/API/_build/html/sites/lib_doc/dataprocessing/02_io.html
  docs/API/_build/html/sites/lib_doc/dataprocessing/02a_management.html
  docs/API/_build/html/sites/lib_doc/dataprocessing/03_inspection.html
  docs/API/_build/html/sites/release_notes/00_overview.html
  docs/API/_build/html/sites/release_notes/01_latest.html
  docs/API/_build/html/sites/release_notes/02_archive.html
  docs/API/sites/lib_doc/overview.rst
  docs/API/sites/release_notes/01_latest.rst
  docs/API/sites/release_notes/02_archive.rst
  quantipy/core/dataset.py
  quantipy/core/quantify/engine.py
  quantipy/sandbox/sandbox.py
Labels: ChainManager, enhancement

#1151 empty result on an array summary stat view now corrected
  quantipy/core/quantify/engine.py
Labels: bug, stack

#1167 I1158 batch additional variables
  quantipy/core/batch.py
  quantipy/core/dataset.py
  quantipy/core/tools/dp/prep.py
Labels: enhancement
