Repository Quantipy/quantipy, pull requests merged in 2018-07, with the labels that each got.

#1041 I1038 bugfix get slicer
  quantipy/core/batch.py
  quantipy/core/dataset.py
  quantipy/core/rules.py
Labels: bug

#1059 fix
  quantipy/core/dataset.py
Labels: DataSet, bug

#1066 Getting additional Batch's text key for add_meta now
  quantipy/core/dataset.py
Labels: bug

#1074 I1071 write dims remove dateformat
  quantipy/core/tools/dp/dimensions/_create_ddf.dms
  quantipy/core/tools/dp/dimensions/writer.py
  quantipy/core/tools/dp/io.py
Labels: enhancement, io

#1079 I1076 text prefix in view recodes
  quantipy/core/stack.py
Labels: DataSet, bug

#1078 date_format dropped
  quantipy/core/dataset.py
Labels: DataSet, bug

#1082 fix indent
  quantipy/core/stack.py
Labels: bug, stack

#1083 I1080 chain toggle bases method
  quantipy/core/stack.py
  quantipy/sandbox/sandbox.py
Labels: enhancement

#1084 I1080 chain toggle bases method
  quantipy/sandbox/sandbox.py
Labels: enhancement

#1087 I1086 fix stack tests
  quantipy/sandbox/sandbox.py
  tests/test_stack.py
Labels: bug, stack
