Repository Quantipy/quantipy, pull requests merged in 2018-06, with the labels that each got.

#1018 Bugfix
  quantipy/core/dataset.py
  quantipy/core/quantify/engine.py
  quantipy/core/stack.py
Labels: bug

#1030 add 2 stage rounding for dataframe and for base description
  quantipy/sandbox/pptx/PptxChainClass.py
Labels: bug, builds

#1040 Catching non-int values for test total chars in Rules.verify_test_value
  quantipy/core/rules.py
Labels: bug

#1043 DataSet.batches() collection and Batch.rename(, ..., refs=True)
  quantipy/core/batch.py
  quantipy/core/dataset.py
Labels: DataSet, enhancement
