Repository Quantipy/quantipy, pull requests merged in 2018-04, with the labels that each got.

#838 ExcelPainter: catch array items by parent tag
  quantipy/core/builds/excel/excel_painter.py
Labels: enhancement

#854 Bug fix for mask base label when elements have equal base sizes
  quantipy/core/builds/powerpoint/pptx_painter.py
  quantipy/core/builds/powerpoint/transformations.py
Labels: bug, builds

#1002 getargspec taken from inspect not decorator in qp_decorators.py.
  quantipy/core/tools/qp_decorators.py
Labels: bug
